name: AxSellwands
version: '${project.version}'
main: com.artillexstudios.axsellwands.AxSellwands
api-version: '1.20'
folia-supported: true

softdepend:
  - AxGens
  - Vault
  - PlayerPoints
  - Essentials
  - ShopGUIPlus
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - PlaceholderAPI
  - PlotSquared
  - Lands
  - GriefPrevention
  - BentoBox
  - WorldGuard
  - SuperiorSkyblock2
  - HuskTowns
  - Towny
  - ExcellentShop
  - HuskClaims
  - Factions
